class Constants():
    MAX_LEN_ING = 128
    MIN_VALUE = 1
    MAX_LEN_UNIT = 64
    MAX_LEN_TAG = 32
    MAX_LEN_RECIPE = 256
    MAX_USER_EMAIL = 254
    MAX_LEN_USER = 150
    MAX_LEN_PASS_USER = 128
