# Generated by Django 3.2.16 on 2024-05-06 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username должен содержать только буквы, цифры  и следующие символы: @/./+/-/_', regex='^[\\w.@+-]+$')], verbose_name='Username'),
        ),
    ]
