# Generated by Django 3.2.16 on 2024-05-19 11:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240518_1001'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_self_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('user', django.db.models.expressions.F('author'))), fields=('user',), name='unique_self_following'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('author')), _negated=True), name='prevent_self_follow'),
        ),
    ]
